export const personalInfo = {
  name: "Filip Sokołowski",
  title: "Lead Software Engineer",
  location: "Wrocław, Poland",
  experience: "14 years",
  email: "filip.sokolowski1990@gmail.com",
  phone: "+48 604 515 975",
  github: "https://github.com/Skarbona",
  linkedin: "https://www.linkedin.com/in/filip-sokolowski-084666152/",
  instagram: "https://www.instagram.com/filip.sokolowski1990/",
  bio: "I am a programmer by profession, a freelancer by choice, a husband by love, a father by heart, and a traveler by passion",
  aboutMe:
    "I’m a product-minded designer and developer who values both high standards and human balance. I work best where clarity, systems thinking, and calm execution matter — especially in complex, fast-moving environments.\n\nFor the past years, I’ve been combining deep professional focus with an intentionally lived life. During the week, I thrive in demanding projects, long hours, and challenging decisions. On weekends, I slow down. While living and traveling in Japan, those moments of calm often came through walking parts of the Henro pilgrimage — the 88-temple route on Shikoku. That deeply spiritual practice helped me reset, regain perspective, and return to work grounded and focused.\n\nThis balance shapes how I work with people and products. I bring reliability under pressure, thoughtful communication, and a long-term mindset. I care about systems that scale, decisions that make sense over time, and teams that feel safe to do great work.\n\nProfessionally, I’m driven, disciplined, and accountable. Personally, I’m curious, reflective, and respectful of different cultures and ways of thinking. I believe the best results come from combining strong execution with empathy and inner stability.\n\nIf you’re looking for someone who delivers, adapts quickly, and stays calm when things get complex — while still being genuinely human — we’ll work well together.",
};

export const keyAchievements = [
  {
    id: 1,
    title: "AI Framework Development",
    description:
      "Developed and implemented a scalable evaluation framework that became the project-wide standard for benchmarking AI models at Mercor, reducing the task cycle by 30%.",
    company: "Mercor",
  },
  {
    id: 2,
    title: "LLM-Generated Applications Enhancement",
    description:
      "Improved quality and reliability of LLM-generated web applications through systematic evaluation and optimization strategies at Mercor.",
    company: "Mercor",
  },
  {
    id: 3,
    title: "Leadership in Internal Projects",
    description:
      "Took a leading role in internal projects at Beeline, optimizing resource management.",
    company: "Beeline",
  },
  {
    id: 4,
    title: "UX/UI Collaboration Excellence",
    description:
      "Played a crucial role in collaboration with UX/UI designers, ensuring seamless integration of design and functionality across platforms.",
    company: "Beeline",
  },
  {
    id: 5,
    title: "Successful Migration Leadership",
    description:
      "Successfully led the migration not only to TypeScript but also to a new CSS framework, improving maintainability and scalability in AI-Driven platform.",
    company: "UBS",
  },
  {
    id: 6,
    title: "Performance Optimization",
    description:
      "Optimized algorithms that reduced processing time by 90%, significantly improving system performance in AI-Driven platform.",
    company: "UBS",
  },
  {
    id: 7,
    title: "Product Development Impact",
    description:
      "Established a position where I had a direct impact on product development, with my insights influencing future implementations and strategic decisions.",
    company: "Beeline",
  },
  {
    id: 8,
    title: "Stakeholder Management",
    description:
      "Delivered comprehensive technical documentation and precise estimations that secured full stakeholder buy-in, effectively de-risking the project and paving the way for a smooth implementation phase.",
    company: "Notch",
  },
];

export const experience = [
  {
    id: 1,
    company: "Notch",
    position: "Frontend Lead",
    period: "September 2025 - Present",
    location: "Remote",
    description: [
      "Spearheaded the discovery phase for a strategic client from Saudi Arabia",
      "Responsible for a comprehensive analysis of the existing technology ecosystem (React, React Native, Next.js, Redux) to identify opportunities for optimization and growth",
      "Led technical workshops with stakeholders to define and solidify functional and non-functional requirements",
      "Developed precise time and resource estimates for the full project implementation lifecycle, including a thorough technical risk assessment",
      "Designed and proposed scalable, high-performance enhancements to the frontend architecture to ensure the product's long-term business value",
      "Established the foundation for the future development process, including defining coding standards and best practices for the engineering team",
    ],
    technologies: ["React", "React Native", "Next.js", "Redux", "Architecture", "Leadership"],
  },
  {
    id: 2,
    company: "Toptal",
    position: "Senior Software Engineer",
    period: "May 2025 - September 2025",
    location: "Remote",
    description: [
      "Strategic Technology Planning: Advise on technology stack selection, solution architecture. Analyze business goals to translate them into specific technical requirements",
      "Technical Oversight and Project Execution: Establishing code quality standards, best practices, and implementing CI/CD processes",
      "Architecture and Development in an Internal Startup: Play a key role in the development of an innovative internal project, where I have a direct and decisive impact on the system's architecture",
    ],
    technologies: [
      "React",
      "GraphQL",
      "Jest",
      "TypeScript",
      "Next.js",
      "Zustand",
      "Tailwind",
      "AI Tools",
      "ChatGPT Pro",
    ],
  },
  {
    id: 3,
    company: "Beeline",
    position: "Senior Software Engineer",
    period: "April 2021 - May 2025",
    location: "Remote",
    description: [
      "Spearheaded multiple internal initiatives to improve business operations and user experience within the company's Vendor Management System (VMS)",
      "Worked closely with UX/UI designers to develop user-friendly solutions that streamlined workforce management for a U.S.-based client",
      "Responsible for full-cycle development, from early-stage consultations to implementation and monitoring of feature performance",
      "Managed key elements of design system, including design tokens, ensuring consistency and scalability across projects",
      "Worked extensively with Storybook to document, test, and streamline UI components for better developer and designer collaboration",
    ],
    technologies: [
      "React",
      "GraphQL",
      "REST API",
      "TypeScript",
      "Jest",
      "WDIO",
      "Storybook",
      "Material UI",
      "Design System",
      "Nx",
    ],
  },
  {
    id: 4,
    company: "UBS",
    position: "Software Engineer",
    period: "April 2019 - April 2021",
    location: "Remote",
    description: [
      "Led the transition from JavaScript to TypeScript and restructured the UX/UI architecture for an AI-powered data extraction platform",
      "Successfully migrated the project to a new CSS framework, improving maintainability and consistency across the application",
      "Implemented optimized algorithms that reduced processing time by 90%, significantly enhancing performance",
    ],
    technologies: [
      "JavaScript",
      "React",
      "TypeScript",
      "Redux",
      "Ant Design",
      "AI",
      "Webpack",
      "Microservices",
    ],
  },
  {
    id: 5,
    company: "Sofomo",
    position: "Front-end Developer",
    period: "April 2018 - April 2019",
    location: "Remote",
    description: [
      "Played a key role in developing an e-commerce platform for Land Rover smartphones, optimizing performance and responsiveness",
      "Contributed to a U.S.-based medical recruitment platform by maintaining core functionalities, improving UI accessibility",
    ],
    technologies: ["React", "JavaScript", "Redux", "WordPress", "CSS", "Bootstrap", "Webpack"],
  },
  {
    id: 6,
    company: "Chili IT Expert Filip Sokolowski",
    position: "Freelancer",
    period: "2012 - Present",
    location: "Remote",
    description: [
      "Developed scalable, high-performance applications and websites for a variety of clients, specializing in modern front-end technologies",
      "Built and customized CMS-based websites using WordPress, focusing on SEO and SEM optimizations",
      "Ensured websites and applications met high standards for usability, security, and performance",
    ],
    technologies: [
      "WordPress",
      "JavaScript",
      "Vue",
      "CSS",
      "Node.js",
      "Express",
      "React",
      "MongoDB",
      "Firebase",
      "CI/CD",
    ],
  },
];

export const consulting = [
  {
    id: 1,
    company: "Mercor",
    position: "AI Model Evaluator - LLM evaluation",
    period: "2025 - Present",
    description: [
      "Consulting for a top-tier AI company from the US",
      "Improving LLM-generated web applications",
      "Implementing a scalable evaluation framework for benchmarking AI models",
      "Provide consulting services in developing new innovative web technologies, focusing on selecting the right tools, designing implementation strategies",
    ],
    technologies: ["AI", "LLM", "Web Technologies", "Consulting"],
  },
];

export const skills = {
  technical: [
    "JavaScript",
    "TypeScript",
    "React",
    "Redux",
    "GraphQL",
    "REST API",
    "Jest",
    "Testing Library",
    "WDIO",
    "Node.js",
    "CI/CD",
    "Storybook",
    "GitHub",
    "GitLab",
    "Confluence",
    "Jira",
    "Webpack",
    "Figma",
    "Vite",
    "Copilot",
    "ChatGPT Pro",
    "Gemini Pro",
    "React Router",
    "Material UI",
    "Design System",
    "Next.js",
    "Tailwind CSS",
  ],
  soft: [
    "Problem-solving",
    "Attention to detail",
    "Responsibility",
    "Teamwork",
    "Flexibility",
    "Perseverance",
    "Leadership",
    "Mentoring",
    "Communication",
    "Collaboration",
    "Adaptability",
    "Innovation",
    "Critical thinking",
    "Time management",
    "Project management",
  ],
  languages: [
    { language: "Polish", level: "Native" },
    { language: "English", level: "Advanced" },
    { language: "Japanese", level: "Beginner" },
  ],
  interests: [
    "Family time",
    "Learning (Japanese!)",
    "Games",
    "Movies",
    "Traveling",
    "Running",
    "Yoga",
  ],
};

export const education = {
  degree: "Master's Degree",
  field: "IT and Econometrics",
  school: "Wrocław University of Economics and Business",
  period: "2009-2016",
  location: "Wrocław, Poland",
};
